---
title: "Project 2"
author: "Eli (Ilya) Bolotin"
date: "10/21/2019"
output: word_document
fontsize: 11
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
# Load libraries
if (!require("pacman")) install.packages("pacman")
pacman::p_load(statnet, devtools, UserNetR, igraph, intergraph, igraphdata, maps, geosphere, proj4)
detach(package:statnet)
```

```{r}
data(USairports)
```

# Visualization and Network Summary

```{r}
# view attribute names
vertex_attr_names(USairports)
edge_attr_names(USairports)

# pull attributes
va <- vertex_attr(USairports)
ea <- edge_attr(USairports)

# view edges and vertices of object
vertices <- V(USairports)
edges <- E(USairports)

# vertices of object
# USairports <- delete_vertex_attr(USairports, "Position")

# Add state as vertex attribute
USairports <- set.vertex.attribute(USairports, "State", index=V(USairports), as.character(sapply(strsplit(V(USairports)$City, ", ", fixed = TRUE), function(x) x[2])))

USairports <- set.vertex.attribute(USairports, "Lat", index=V(USairports), as.character(sapply(strsplit(V(USairports)$Position, " ", fixed = TRUE), function(x) x[1])))

USairports <- set.vertex.attribute(USairports, "Long", index=V(USairports), as.character(sapply(strsplit(V(USairports)$Position, " ", fixed = TRUE), function(x) x[2])))

# View vertex attributes after
va <- vertex_attr(USairports)
va_names <- names(va)
```



```{r}
xy <- data.frame(matrix(c(V(USairports)$Long,V(USairports)$Lat), ncol=2))

library(proj4)
proj4string <- "+proj=utm +zone=19 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs "

# Transformed data
pj <- project(xy, proj4string, inverse=TRUE)
latlon <- data.frame(lat=pj$y, lon=pj$x)
print(latlon)
```


## map

```{r}
map("state", col="grey20", fill=TRUE, bg="black", lwd=0.1)

# Add a point on the map for each airport:
points(x=latlon$lat, y=latlon$lon, pch=19, cex=10, col="orange")
```

## initial plot
```{r}
set.seed(10)
USairports <- simplify(USairports, remove.multiple = T, remove.loops = T)
plot(USairports, vertex.label=NA, vertex.size=1, vertex.label.cex = .8, vertex.label.dist=2, edge.arrow.size = .2, layout=layout_with_fr(USairports), col=rgb(.25, .5, .3, alpha=.5))
```

## filtering
```{r}
'%ni%' <- Negate('%in%')
# USairports <- simplify(USairports, remove.multiple = T, remove.loops = T)
inCal <- grepl("CA$", V(USairports)$City) 
inNy <- grepl("NY$", V(USairports)$City)
# ny_ca <- E(USairports)[V(USairports)[inCal] %->% V(USairports)[inNy]]
# new_graph <- graph_from_edgelist(ny_ca)
subv = c(V(USairports)[inCal], V(USairports)[inNy])
# calAirports <- induced_subgraph(USairports, inCal)
# nyAirports <- induced_subgraph(USairports, inNy)
bothAirports <- induced_subgraph(USairports, vids=subv)
# bothAirports <- simplify(bothAirports, remove.multiple = T, remove.loops = T)
# USairports <- delete_vertices(USairports, V(USairports)[c("CA","NY") != V(USairports)$State])
```

## colors

```{r}
vertex_attr(bothAirports)$color<-rep("#FF9C0B", length(V(bothAirports))) #coloring all the nodes orange
#Selecting everyone that is "TRUE" in $type to change it to green (take a look at the help of the grep function in case you don't know it).
vertex_attr(bothAirports)$color[grep(pattern = "NY", vertex_attr(bothAirports)$State)]<-"#1C912C"
vertex_attr(bothAirports)$color # checking the color vector
```

## both airports
```{r}
set.seed(10)
bothAirports <- simplify(bothAirports, remove.multiple = T, remove.loops = T)
l = layout_with_fr(bothAirports)
plot(bothAirports, vertex.label=NA, vertex.color = vertex_attr(bothAirports)$color, vertex.size=igraph::degree(bothAirports), vertex.label.cex = .8, vertex.label.dist=2, edge.arrow.size = .2, layout=l)
```

## all airports
```{r}
set.seed(4)
# plot(g4s, vertex.label=V(USairports)$State, vertex.size=1, vertex.label.dist=1, edge.arrow.size = 0)
plot(USairports, vertex.label=NA, vertex.size=1, vertex.label.dist=1, edge.arrow.size = 0, layout=l)
```

```{r}
# d2Vertices <- ego(USairports, nodes = c("JFK","LAX"), order=2)
# JFKNet <- make_ego_graph(USairports, nodes = "JFK", order=2)[[1]]
```


```{r}
# convert back for exporting
# as_data_frame(net, what="edges")
# as_data_frame(net, what="vertices")
```

```{r}
# convert coordinates
# df <- asDF(USairports) # this works
# net1 <- asNetwork(df$edges, vertices=df$vertexes)
```


# Community Detection

# Network modeling


```{r}
net1 %v% 'lat' <- as.character(sapply(strsplit(get.vertex.attribute(net1, "Position"), " ", fixed = TRUE), function(x) x[1]))

net1 %v% 'long' <- as.character(sapply(strsplit(get.vertex.attribute(net1, "Position"), " ", fixed = TRUE), function(x) x[2]))

proj4string <- "+proj=utm +zone=19 +ellps=WGS84 +units=m +no_defs"

xy = data.frame(matrix(c(get.vertex.attribute(net1, "lat"),get.vertex.attribute(net1, "long")), nc=2))
colnames(xy) <- c("lat","long")

# Transformed data
pj <- project(xy, proj4string, inverse=TRUE)
latlon <- data.frame(lat=pj$y, lon=pj$x)
print(latlon)
```