---
title: "Untitled"
author: "Eli (Ilya) Bolotin"
date: "9/30/2019"
output: pdf_document
---



```{r message=FALSE, warning=FALSE}
library(statnet)
library(devtools)
library(UserNetR)
library(igraph)
library(intergraph)
```
















```{r message=FALSE, warning=FALSE}
library(statnet)
library(devtools)
library(UserNetR)
data(Moreno)
data(DHHS)
data(Bali)
```

```{r}
data(Bali)
summary(Bali)
rolelab <- get.vertex.attribute(Bali,"role")
gplot(Bali,usearrows=FALSE,label=rolelab,  displaylabels=T,label.col="darkblue")
```


```{r}
network.size(DHHS)
```

```{r}
gden(DHHS)
```

```{r}
plot(DHHS)
plot(Moreno)
```

```{r}
Moreno1<-get.inducedSubgraph(Moreno,which(Moreno %v% "gender"=="1"))
gden(Moreno1)
```

```{r}
# summary(DHHS)
"NIH-20" %in% get.vertex.attribute(DHHS, "vertex.names") 
```


```{r}
netmat<-rbind(c("A","B"),
              c("A","C"),
              c("B","C"),
              c("B","D"),
              c("C","E"))
netmatdf<-data.frame(netmat)
netmatdf
netmat.edge<-netmatdf
netmat.graph<-network(netmat.edge,matrix.type="edgelist")
summary(netmat.graph)
gden(netmat.graph)
gplot(netmat.graph,displaylabels=TRUE)
```


```{r}
data(Bali)
summary(Bali)
rolelab <- get.vertex.attribute(Bali,"role")
plot(Bali,usearrows=FALSE,label=rolelab,  displaylabels=T,label.col="darkblue")
```

```{r}
library(statnet)
data(Moreno)
library(intergraph)
op<-par(mar=rep(0,4),mfrow=c(1,3)) #repeat 0 four times
plot(Moreno,mode="circle",vertex.cex=1.5,main="Cirlce",displaylabels=TRUE)
plot(Moreno,mode="fruchtermanreingold",vertex.cex=3.5,main="FR",displaylabels=TRUE)
plot(Moreno,mode="kamadakawai",vertex.cex=1.5,main="KW",displaylabels=TRUE)
par(op)
```

```{r}
as.sociomatrix.sna(Bali)[1:6,1:6]
```

```{r}
library(igraph)
g <- graph_from_literal(A--B, B--C, B--D,C--E,D--E)
plot(g)
plot(g, edge.width=3,
     vertex.color="orange",
     vertex.label.color="black",
     vertex.label.cex=1.2,
     vertex.size=50)
bc<-betweenness(g) #returns non-normalized betweenness centrality
bc
centr_betw(g, directed = FALSE)$res  #another way of gettting same thing
plot(g, edge.width=3,
     vertex.color="orange",
     vertex.label.color="black",
     vertex.label.cex=1.2,
     vertex.size=50,
     vertex.label=bc)
```

```{r}
library(igraph)
g2 <- graph_from_literal(1--2,2--3,1--3,3--4,4--5,5--6,5--7,6--7)
plot(g2)
plot(g2, edge.width=3,
     vertex.color="orange",
     vertex.label.color="black",
     vertex.label.cex=1.2,
     vertex.size=30)
bc2<-betweenness(g2) #returns non-normalized betweenness centrality
bc2
plot(g2, edge.width=3,
     vertex.color="orange",
     vertex.label.color="black",
     vertex.label.cex=1.2,
     vertex.size=30,
     vertex.label=bc2)
```

```{r}
library(igraph)
g <- graph_from_literal(A--B, B--C, C--D, D--E, E--F)
plot(g)
plot(g, edge.width=3,
     vertex.color="orange",
     vertex.label.color="black",
     vertex.label.cex=1.2,
     vertex.size=50)
bc<-betweenness(g) #returns non-normalized betweenness centrality
bc
centr_betw(g, directed = FALSE)$res  #another way of gettting same thing
plot(g, edge.width=3,
     vertex.color="orange",
     vertex.label.color="black",
     vertex.label.cex=1.2,
     vertex.size=50,
     vertex.label=bc)
```


```{r}
library(igraph)
library(intergraph)
data(DHHS)
```

```{r}
library(UserNetR)
library(igraph)
library(intergraph)
data(Bali)
iBali <- asIgraph(Bali) 
deg <- degree(iBali)
summary(deg)
```


```{r}
iDHHS <- asIgraph(DHHS) 
```

```{r}
one <- cluster_edge_betweenness(iDHHS)
two <- cluster_spinglass(iDHHS)
three <- cluster_fast_greedy(iDHHS)
four <- cluster_leading_eigen(iDHHS)

```

```{r}
library(UserNetR)
data(middleschool)
ims <- asIgraph(middleschool) 
```

```{r}
five = cluster_walktrap(ims)
```

```{r}
library(UserNetR)
data(hwd)
hwd <- asIgraph(middleschool) 
```


```{r}
coreness <- graph.coreness(hwd)
```

```{r}
get.vertex.attribute(hwd, name='IMDBrating',  index=V(hwd)) 
```

```{r}
library(intergraph)
library(UserNetR)
data(hwd)
```

```{r}
ihwd <- asIgraph(hwd)
graph.density(ihwd) 
```

```{r}
library(UserNetR)
data(hwd)
library(intergraph)
coreness <- graph.coreness(hwd)
maxCoreness <- max(coreness)
```

```{r}
iDHHS <- subgraph.edges(hwd,V(hwd)["IMDBrating (v/n)" > 8])
graph.density(iDHHS) 
# iDHHS <- subgraph.edges(iDHHS,E(iDHHS)[collab > 2])
```

```{r}
colors <- rainbow(maxCoreness) 
V(hwd)$name <- coreness
V(hwd)$color <- colors[coreness]
iDHHS2_6 <- induced.subgraph(hwd,  vids=which(coreness > 5))
lay <- layout.fruchterman.reingold(hwd)
plot(iDHHS2_6,layout=lay,main="All k-cores") 
```

```{r}
h1 <- hwd
h2 <- subgraph.edges(h1, E(h1)[inc(V(h1)[name %in%  c("The Dark Knight Rises", "Inception",  "Batman Begins", "The Lord of the Rings")])])
plot(h2, layout = layout_with_kk) 
```

```{r}
V(h1)$IMDBrating["IMDBrating" %in%  c("The Dark Knight Rises", "Inception",  "Batman Begins", "The Lord of the Rings")] 
```

