---
title: "Project 1: Visualizations"
author: "Eli (Ilya) Bolotin"
date: "9/19/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(reshape)
library(ggrepel)
```

## Load and transform data
```{r message=FALSE, warning=FALSE}
# Load data
world_stats <- read.csv("data.csv")

# Drop some columns, rows
world_stats <- select(world_stats, -c(Series.Code, Country.Code))
world_stats <- world_stats[-c((nrow(world_stats)-5):nrow(world_stats)),]

# Rename year columns
cols_containing_x <- names(world_stats[, grepl( "X" , names(world_stats) )])
new_names <- substring(cols_containing_x, 2, 5)
colnames(world_stats)[colnames(world_stats) %in% cols_containing_x] <- new_names

# Reshape data
md <- melt(world_stats, id=(c("Country.Name","Series.Name")))
world_stats <- cast(md, "Country.Name+variable~Series.Name")
world_stats <- world_stats[,-c(5,12:16)]

# rename metrics
colnames(world_stats)[c(2,3,4,5,6,7,8,9,10,11)] <- c("year","adolescent_fertility","gdp","life_expectancy","mortality_rate","net_migration","prem","pop_growth","pop_total","surface_area")

as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}

world_stats_numerics <- lapply(world_stats[,c(3:dim(world_stats)[2])], as.numeric.factor)
world_stats_numerics <- as.data.frame(world_stats_numerics)
world_stats <- cbind(world_stats[,c(1,2)],world_stats_numerics)

# world_stats$gdp <- as.numeric(levels(world_stats$gdp))[world_stats$gdp]
# world_stats$gdp <- as.character.factor(world_stats$gdp)
# world_stats$mortality_rate <- as.numeric(levels(world_stats$mortality_rate))[world_stats$mortality_rate]
# world_stats$pop_total <- as.numeric(levels(world_stats$pop_total))[world_stats$pop_total]

world_stats$gdp <- world_stats$gdp/(1000000000)
world_stats$gdp <- world_stats$gdp/(1000000000)
```

## Add corruption index to data

```{r}
# create corruption index lookup table
ci_df <- read.csv("cpi.csv", sep=";")
ci_df <- ci_df[,-c(1,2,4,7)]
ci_df <- ci_df[ci_df$time==2018,c(1,3)]
colnames(ci_df) <- c("Country.Name","cpi")
ci_df$Country.Name <- as.character(ci_df$Country.Name)
```

## Synchronize names between tables

```{r}
countries_ws <- levels(droplevels(world_stats$Country.Name))
countries_ci <- ci_df$Country.Name

already_renamed = list()
idx = 0
'%ni%' <- Negate('%in%')

for(country in countries_ws) {
  j = agrep(country, countries_ci, ignore.case = FALSE, value = FALSE, max.distance = 0.1)
  if(length(j) == 1) {
    levels(world_stats$Country.Name)[levels(world_stats$Country.Name) == country] <- ci_df$Country.Name[j]
    already_renamed[idx] <- ci_df$Country.Name[j]
  }
  idx = idx + 1
}

for(i in 1:nrow(ci_df)) {
  if(ci_df$Country.Name[i] %ni% already_renamed) {
    j = agrep(ci_df$Country.Name[i], countries_ws, ignore.case = FALSE, value = FALSE, max.distance = 0.1)
    if(length(j) == 1) {
      ci_df$Country.Name[i] <- countries_ws[j]
    }
  }
}
```

## Add categorical features

```{r message=FALSE, warning=FALSE}
world_stats <- full_join(world_stats, ci_df, by = "Country.Name")

# update world stats table with corruption level
world_stats <- world_stats %>% mutate(ci_rating = case_when(
                                      cpi >= 120  ~ "very corrupt",
                                      cpi < 120 & cpi >= 70 ~ "corrupt",
                                      cpi < 70 & cpi >= 50 ~ "somewhat corrupt",
                                      cpi < 50 & cpi >= 25 ~ "clean",
                                      cpi < 25 ~ "very clean"))

world_stats <- world_stats %>% mutate(mortality_cat = case_when(
                                      mortality_rate <= 15 ~ "low",
                                      mortality_rate > 15 & mortality_rate <= 30 ~ "medium",
                                      mortality_rate > 30 ~ "high"))

# drop NAs
world_stats <- world_stats[which(!is.na(world_stats$gdp) & !is.na(world_stats$cpi) & !is.na(world_stats$mortality_cat)),]

# create df for 2018
world_stats_2018 = world_stats[world_stats$year==2018,]
world_stats_2018$ci_rating <- factor(world_stats_2018$ci_rating, levels = c("very clean", "clean", "somewhat corrupt", "corrupt", "very corrupt"))
```

## Graph 1

```{r}
ggplot(data = world_stats_2018)+
  geom_point(aes(x=cpi, y=mortality_rate, fill=gdp)) + 
  scale_x_continuous(labels = scales::comma)
```

## Graph 2

```{r}
p <- ggplot(data = world_stats_2018, aes(x=cpi, y=mortality_rate))
p + geom_point(aes(colour = factor(ci_rating)), size = 4) +
  geom_point(colour = "grey90", size = 1.5) +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))
```

## Graph 3

```{r}
p <- ggplot(data = world_stats_2018, aes(x=cpi, y=mortality_rate))
p + geom_point(aes(colour = factor(ci_rating), size = gdp)) +
  scale_size("GDP", breaks=c(5000,10000,15000,20000), labels=c("$5t","$10t","$15t","$20t")) +    
  scale_colour_brewer(palette = "RdYlGn", 
                      direction=-1, 
                      name = "Corruption Level", 
                      labels = c("very clean", "clean", "somewhat corrupt", "corrupt", "very corrupt")) +
  # geom_point(aes(size = pop_total)) +
  # geom_point(colour = "grey100", size = 1.5) +
  geom_text_repel(
    data = subset(world_stats_2018, Country.Name %in% c("United States of America","Canada","China","Brazil","Portugal","Italy","India","Denmark","Russian Federation","Angola")), 
    aes(label=Country.Name),
    nudge_y      = 55,
    direction    = "y",
    angle        = 0,
    segment.color = "grey50",
    segment.size = .2,
    segment.alpha = .5,
    size = 3.5,
    point.padding = 1,
    arrow = arrow(length=unit(0.03,"npc"), type="closed"),
    vjust = 0) +
  theme_bw() + theme(panel.border = element_blank(), 
                     panel.grid.major = element_blank(),
                      panel.grid.minor = element_blank(), 
                     axis.line = element_line(colour = "black")) +
  labs(title="Global Infant Mortality vs Corruption and GDP", 
       subtitle = "Data collected from World Bank and Corruption Perception Index",
       x ="Corruption Perception Index", 
       y = "Infant mortality Rate (in 1000 live births)") + 
  theme(plot.title = element_text(size=18),
        plot.subtitle = element_text(size=10),
        axis.text.x = element_text(size=11), 
        axis.text.y = element_text(size=11), 
        axis.title.x = element_text(size=10),
        axis.title.y = element_text(size=10))
```







